language: android

android:
  components:
    - build-tools-24.0.0
    - android-19
    - sysimg-19
    - extra-android-support
  licenses:
    - android-sdk-license-bcbbd656
script:
    - chmod +x gradlew
    - ./gradlew build test
