language: android

android:
  components:
    - build-tools-21.1.1
    - android-21
    - sysimg-21
    - extra-android-support
  licenses:
    - android-sdk-license-bcbbd656
script:
    - chmod +x gradlew
    - ./gradlew build test
